# -*- coding: utf-8 -*-
"""agent_feature_creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tXYApTyhJgJCPTXAW-VeVX_68Jc2t2m
"""

# =============================================================================
# SELF-DRIVING PORTFOLIO: EXTENDED FEATURE CREATION CALLABLES
# =============================================================================
# Implements the deterministic feature engineering functions required to
# synthesize missing columns prior to tool invocation in the agentic Strategic
# Asset Allocation (SAA) pipeline described in:
#   Ang, Azimbayev, and Kim (2026) — "The Self-Driving Portfolio"
#
# This module enforces strict mathematical exactitude and software engineering
# rigor. It handles cross-sectional and time-series indexing flawlessly,
# ensuring that no silent numerical drift occurs during data preparation.
#
# All functions are purely deterministic Python callables.
# =============================================================================

from __future__ import annotations

import logging
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Module-level logger
# ---------------------------------------------------------------------------
# Initialise a named logger so callers can configure log levels independently
logger: logging.Logger = logging.getLogger(__name__)


def compute_cpi_mom(
    df_macro_raw: pd.DataFrame,
    df_cpi_index_raw: pd.DataFrame
) -> pd.DataFrame:
    """
    Computes the Month-over-Month (MoM) CPI inflation rate and merges it into
    the macro dataset.

    Equation: cpi_mom_t = (cpi_index_level_t / cpi_index_level_{t-1}) - 1

    Parameters
    ----------
    df_macro_raw : pd.DataFrame
        The primary macro dataset with a DatetimeIndex.
    df_cpi_index_raw : pd.DataFrame
        The CPI dataset containing 'cpi_index_level' with a DatetimeIndex.

    Returns
    -------
    pd.DataFrame
        A new dataframe containing the original macro data and the computed
        'cpi_mom'.

    Raises
    ------
    TypeError
        If inputs are not pandas DataFrames or lack a DatetimeIndex.
    ValueError
        If 'cpi_index_level' is missing from the CPI dataframe.
    """
    # ------------------------------------------------------------------
    # Input validation: type checks
    # ------------------------------------------------------------------
    if not isinstance(df_macro_raw, pd.DataFrame):
        raise TypeError(f"df_macro_raw must be a pandas DataFrame, got {type(df_macro_raw).__name__}.")

    if not isinstance(df_cpi_index_raw, pd.DataFrame):
        raise TypeError(f"df_cpi_index_raw must be a pandas DataFrame, got {type(df_cpi_index_raw).__name__}.")

    # ------------------------------------------------------------------
    # Input validation: index checks
    # ------------------------------------------------------------------
    if not isinstance(df_macro_raw.index, pd.DatetimeIndex):
        raise TypeError("df_macro_raw must have a DatetimeIndex.")

    if not isinstance(df_cpi_index_raw.index, pd.DatetimeIndex):
        raise TypeError("df_cpi_index_raw must have a DatetimeIndex.")

    # ------------------------------------------------------------------
    # Input validation: required columns
    # ------------------------------------------------------------------
    if 'cpi_index_level' not in df_cpi_index_raw.columns:
        raise ValueError("df_cpi_index_raw must contain the column 'cpi_index_level'.")

    # ------------------------------------------------------------------
    # Create deep copies to preserve immutability of inputs
    # ------------------------------------------------------------------
    df_macro_out: pd.DataFrame = df_macro_raw.copy(deep=True)
    df_cpi_calc: pd.DataFrame = df_cpi_index_raw.copy(deep=True)

    # ------------------------------------------------------------------
    # Sort the CPI dataframe chronologically to ensure accurate percentage
    # change calculations
    # ------------------------------------------------------------------
    df_cpi_calc = df_cpi_calc.sort_index()

    # ------------------------------------------------------------------
    # Compute the discrete periodic rate of change (MoM) without
    # forward-filling NaNs
    # ------------------------------------------------------------------
    cpi_mom_series: pd.Series = df_cpi_calc['cpi_index_level'].pct_change(periods=1, fill_method=None)

    # Rename the resulting series to match the target schema
    cpi_mom_series.name = 'cpi_mom'

    # ------------------------------------------------------------------
    # Merge the computed series into the macro dataframe using a left join
    # on the index to prevent data leakage or row duplication
    # ------------------------------------------------------------------
    df_macro_out = df_macro_out.join(cpi_mom_series, how='left')

    logger.info("Successfully computed and merged 'cpi_mom' into macro dataset.")

    return df_macro_out


def compute_fed_funds_3m_change(df_macro_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Computes the 3-month discrete difference in the Federal Funds Rate.

    Equation: fed_funds_3m_change_t = fed_funds_rate_t - fed_funds_rate_{t-3}

    Parameters
    ----------
    df_macro_raw : pd.DataFrame
        The macro dataset containing 'fed_funds_rate' with a DatetimeIndex.

    Returns
    -------
    pd.DataFrame
        A new dataframe containing the computed 'fed_funds_3m_change'.

    Raises
    ------
    TypeError
        If input is not a DataFrame or lacks a DatetimeIndex.
    ValueError
        If 'fed_funds_rate' is missing.
    """
    # ------------------------------------------------------------------
    # Input validation: type and index checks
    # ------------------------------------------------------------------
    if not isinstance(df_macro_raw, pd.DataFrame):
        raise TypeError(f"df_macro_raw must be a pandas DataFrame, got {type(df_macro_raw).__name__}.")

    if not isinstance(df_macro_raw.index, pd.DatetimeIndex):
        raise TypeError("df_macro_raw must have a DatetimeIndex.")

    # ------------------------------------------------------------------
    # Input validation: required columns
    # ------------------------------------------------------------------
    if 'fed_funds_rate' not in df_macro_raw.columns:
        raise ValueError("df_macro_raw must contain the column 'fed_funds_rate'.")

    # ------------------------------------------------------------------
    # Create a deep copy to preserve immutability
    # ------------------------------------------------------------------
    df_out: pd.DataFrame = df_macro_raw.copy(deep=True)

    # ------------------------------------------------------------------
    # Sort the dataframe chronologically to ensure accurate difference calculations
    # ------------------------------------------------------------------
    df_out = df_out.sort_index()

    # ------------------------------------------------------------------
    # Compute the 3-period discrete difference for the fed funds rate
    # ------------------------------------------------------------------
    df_out['fed_funds_3m_change'] = df_out['fed_funds_rate'].diff(periods=3)

    logger.info("Successfully computed 'fed_funds_3m_change'.")

    return df_out


def compute_financial_conditions_mom(df_macro_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Computes the 1-month discrete difference in the Financial Conditions Index (FCI).

    Equation: financial_conditions_mom_t = fci_raw_score_t - fci_raw_score_{t-1}

    Parameters
    ----------
    df_macro_raw : pd.DataFrame
        The macro dataset containing 'fci_raw_score' with a DatetimeIndex.

    Returns
    -------
    pd.DataFrame
        A new dataframe containing the computed 'financial_conditions_mom'.

    Raises
    ------
    TypeError
        If input is not a DataFrame or lacks a DatetimeIndex.
    ValueError
        If 'fci_raw_score' is missing.
    """
    # ------------------------------------------------------------------
    # Input validation: type and index checks
    # ------------------------------------------------------------------
    if not isinstance(df_macro_raw, pd.DataFrame):
        raise TypeError(f"df_macro_raw must be a pandas DataFrame, got {type(df_macro_raw).__name__}.")

    if not isinstance(df_macro_raw.index, pd.DatetimeIndex):
        raise TypeError("df_macro_raw must have a DatetimeIndex.")

    # ------------------------------------------------------------------
    # Input validation: required columns
    # ------------------------------------------------------------------
    if 'fci_raw_score' not in df_macro_raw.columns:
        raise ValueError("df_macro_raw must contain the column 'fci_raw_score'.")

    # ------------------------------------------------------------------
    # Create a deep copy to preserve immutability
    # ------------------------------------------------------------------
    df_out: pd.DataFrame = df_macro_raw.copy(deep=True)

    # ------------------------------------------------------------------
    # Sort the dataframe chronologically to ensure accurate difference calculations
    # ------------------------------------------------------------------
    df_out = df_out.sort_index()

    # ------------------------------------------------------------------
    # Compute the 1-period discrete difference for the FCI score
    # ------------------------------------------------------------------
    df_out['financial_conditions_mom'] = df_out['fci_raw_score'].diff(periods=1)

    logger.info("Successfully computed 'financial_conditions_mom'.")

    return df_out


def compute_periodic_returns(df_total_return_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Computes the discrete periodic returns for a panel of assets, strictly
    preventing cross-sectional leakage.

    Equation: r_{t,i} = (TR_{t,i} / TR_{t-1,i}) - 1

    Parameters
    ----------
    df_total_return_raw : pd.DataFrame
        The total return dataset with a MultiIndex ['date', 'ticker',
        'investment_universe'] and column 'total_return_index'.

    Returns
    -------
    pd.DataFrame
        A new dataframe containing the computed 'periodic_return'.

    Raises
    ------
    TypeError
        If input is not a DataFrame or lacks the required MultiIndex.
    ValueError
        If 'total_return_index' is missing or contains non-positive values.
    """
    # ------------------------------------------------------------------
    # Input validation: type checks
    # ------------------------------------------------------------------
    if not isinstance(df_total_return_raw, pd.DataFrame):
        raise TypeError(f"df_total_return_raw must be a pandas DataFrame, got {type(df_total_return_raw).__name__}.")

    # ------------------------------------------------------------------
    # Input validation: MultiIndex checks
    # ------------------------------------------------------------------
    if not isinstance(df_total_return_raw.index, pd.MultiIndex):
        raise TypeError("df_total_return_raw must have a MultiIndex.")

    required_levels: List[str] = ['date', 'ticker', 'investment_universe']

    for level in required_levels:
        if level not in df_total_return_raw.index.names:
            raise ValueError(f"MultiIndex must contain the level '{level}'.")

    # ------------------------------------------------------------------
    # Input validation: required columns and value constraints
    # ------------------------------------------------------------------
    if 'total_return_index' not in df_total_return_raw.columns:
        raise ValueError("df_total_return_raw must contain the column 'total_return_index'.")

    if (df_total_return_raw['total_return_index'] <= 0).any():
        raise ValueError("All values in 'total_return_index' must be strictly positive.")

    # ------------------------------------------------------------------
    # Create a deep copy to preserve immutability
    # ------------------------------------------------------------------
    df_out: pd.DataFrame = df_total_return_raw.copy(deep=True)

    # ------------------------------------------------------------------
    # Sort the MultiIndex first by the cross-sectional identifiers, then chronologically
    # ------------------------------------------------------------------
    df_out = df_out.sort_index(level=['ticker', 'investment_universe', 'date'])

    # ------------------------------------------------------------------
    # Group by the cross-sectional identifiers and compute the percentage
    # change chronologically
    # ------------------------------------------------------------------
    df_out['periodic_return'] = df_out.groupby(
        level=['ticker', 'investment_universe']
    )['total_return_index'].pct_change(periods=1, fill_method=None)

    logger.info("Successfully computed 'periodic_return' for panel data.")

    return df_out


def aggregate_daily_factors_to_monthly(
    df_benchmark_factors_raw: pd.DataFrame,
    is_rf_annualized: bool = True
) -> pd.DataFrame:
    """
    Aggregates daily factor returns and the risk-free rate into monthly
    geometric returns.

    Equation: R_{monthly} = \prod_{d=1}^{D} (1 + r_{daily, d}) - 1
    If is_rf_annualized is True, the daily rf is first de-annualized:
    rf_daily = rf_ann / 365.

    Parameters
    ----------
    df_benchmark_factors_raw : pd.DataFrame
        Daily dataset containing 'mkt_rf', 'smb', 'hml', 'rf'.
    is_rf_annualized : bool, optional
        Flag indicating if 'rf' is provided as an annualized yield. Defaults to True.

    Returns
    -------
    pd.DataFrame
        A new dataframe with a monthly (Month-End) DatetimeIndex containing
        compounded returns.

    Raises
    ------
    TypeError
        If input is not a DataFrame or lacks a DatetimeIndex.
    ValueError
        If required factor columns are missing.
    """
    # ------------------------------------------------------------------
    # Input validation: type and index checks
    # ------------------------------------------------------------------
    if not isinstance(df_benchmark_factors_raw, pd.DataFrame):
        raise TypeError(f"df_benchmark_factors_raw must be a pandas DataFrame, got {type(df_benchmark_factors_raw).__name__}.")

    if not isinstance(df_benchmark_factors_raw.index, pd.DatetimeIndex):
        raise TypeError("df_benchmark_factors_raw must have a DatetimeIndex.")

    # ------------------------------------------------------------------
    # Input validation: required columns
    # ------------------------------------------------------------------
    required_cols: List[str] = ['mkt_rf', 'smb', 'hml', 'rf']

    for col in required_cols:
        if col not in df_benchmark_factors_raw.columns:
            raise ValueError(f"df_benchmark_factors_raw must contain the column '{col}'.")

    # ------------------------------------------------------------------
    # Create a deep copy to preserve immutability
    # ------------------------------------------------------------------
    df_calc: pd.DataFrame = df_benchmark_factors_raw.copy(deep=True)

    # ------------------------------------------------------------------
    # Sort the dataframe chronologically
    # ------------------------------------------------------------------
    df_calc = df_calc.sort_index()

    # ------------------------------------------------------------------
    # De-annualize the risk-free rate if necessary
    # ------------------------------------------------------------------
    if is_rf_annualized:
        df_calc['rf'] = df_calc['rf'] / 365.0

    # ------------------------------------------------------------------
    # Add 1 to all daily returns to prepare for geometric compounding
    # ------------------------------------------------------------------
    df_gross: pd.DataFrame = df_calc[required_cols] + 1.0

    # ------------------------------------------------------------------
    # Group by Month-End ('ME') and calculate the product of the gross returns
    # ------------------------------------------------------------------
    df_monthly_gross: pd.DataFrame = df_gross.groupby(pd.Grouper(freq='ME')).prod()

    # ------------------------------------------------------------------
    # Subtract 1 to convert the compounded gross returns back to net periodic returns
    # ------------------------------------------------------------------
    df_monthly_net: pd.DataFrame = df_monthly_gross - 1.0

    logger.info("Successfully aggregated daily factors to monthly geometric returns.")

    return df_monthly_net


# =============================================================================
# ORCHESTRATOR: orchestrate_feature_creation
# =============================================================================

def orchestrate_feature_creation(
    df_macro_raw: pd.DataFrame,
    df_cpi_index_raw: pd.DataFrame,
    df_total_return_raw: pd.DataFrame,
    df_benchmark_factors_raw: pd.DataFrame,
    is_rf_annualized: bool = True
) -> Dict[str, pd.DataFrame]:
    """
    Orchestrates the deterministic feature engineering pipeline to synthesize
    all missing columns required by the agentic SAA tools.

    This function acts as the centralized controller for data preparation,
    sequentially invoking the individual feature creation callables and
    ensuring that the resulting data structures are fully populated and
    mathematically rigorous prior to downstream agent consumption.

    Parameters
    ----------
    df_macro_raw : pd.DataFrame
        The primary macro dataset.
    df_cpi_index_raw : pd.DataFrame
        The CPI dataset for inflation momentum computation.
    df_total_return_raw : pd.DataFrame
        The total return panel dataset for periodic return computation.
    df_benchmark_factors_raw : pd.DataFrame
        The daily factor dataset for monthly geometric aggregation.
    is_rf_annualized : bool, optional
        Flag indicating if the risk-free rate in the factor dataset is
        annualized. Defaults to True.

    Returns
    -------
    Dict[str, pd.DataFrame]
        A dictionary containing the fully processed and augmented dataframes:
        - 'df_macro_processed': Augmented with cpi_mom, fed_funds_3m_change,
          and financial_conditions_mom.
        - 'df_total_return_processed': Augmented with periodic_return.
        - 'df_benchmark_factors_monthly': Aggregated to monthly geometric returns.

    Raises
    ------
    RuntimeError
        If any step in the feature creation pipeline fails.
    """
    logger.info("Starting feature creation orchestration pipeline.")

    try:
        # ------------------------------------------------------------------
        # Step 1: Compute CPI MoM and merge into the macro dataset
        # ------------------------------------------------------------------
        logger.info("Step 1: Computing CPI MoM.")
        df_macro_step1: pd.DataFrame = compute_cpi_mom(
            df_macro_raw=df_macro_raw,
            df_cpi_index_raw=df_cpi_index_raw
        )

        # ------------------------------------------------------------------
        # Step 2: Compute Fed Funds 3M change on the updated macro dataset
        # ------------------------------------------------------------------
        logger.info("Step 2: Computing Fed Funds 3M change.")
        df_macro_step2: pd.DataFrame = compute_fed_funds_3m_change(
            df_macro_raw=df_macro_step1
        )

        # ------------------------------------------------------------------
        # Step 3: Compute Financial Conditions MoM on the updated macro dataset
        # ------------------------------------------------------------------
        logger.info("Step 3: Computing Financial Conditions MoM.")
        df_macro_processed: pd.DataFrame = compute_financial_conditions_mom(
            df_macro_raw=df_macro_step2
        )

        # ------------------------------------------------------------------
        # Step 4: Compute periodic returns for the total return panel
        # ------------------------------------------------------------------
        logger.info("Step 4: Computing periodic returns for panel data.")
        df_total_return_processed: pd.DataFrame = compute_periodic_returns(
            df_total_return_raw=df_total_return_raw
        )

        # ------------------------------------------------------------------
        # Step 5: Aggregate daily factors to monthly geometric returns
        # ------------------------------------------------------------------
        logger.info("Step 5: Aggregating daily factors to monthly.")
        df_benchmark_factors_monthly: pd.DataFrame = aggregate_daily_factors_to_monthly(
            df_benchmark_factors_raw=df_benchmark_factors_raw,
            is_rf_annualized=is_rf_annualized
        )

        logger.info("Feature creation orchestration pipeline completed successfully.")

        # ------------------------------------------------------------------
        # Return the processed dataframes in a structured dictionary
        # ------------------------------------------------------------------
        return {
            "df_macro_processed": df_macro_processed,
            "df_total_return_processed": df_total_return_processed,
            "df_benchmark_factors_monthly": df_benchmark_factors_monthly
        }

    except Exception as e:
        # Catch any exception, log the failure, and raise a RuntimeError to halt the pipeline
        logger.error("Feature creation pipeline failed: %s", str(e))
        raise RuntimeError(f"Feature creation pipeline failed: {str(e)}") from e